import base64
import zlib

# ENCRYPTED AND COMPRESSED APP.PY
# Decrypt with: python -c "import base64,zlib; exec(zlib.decompress(base64.b64decode('...')))"

ENCRYPTED_APP = """
eJy1Ustu2zAM/BXDO1YZzBhLtjPs2AG7YBgGbMOGbetRFnSLcN3YiCj1q/f97pmULXdAcQgEAuQ9
hyJVzw9LySZaKKnfWw7k4OcF8pn3zM3CJ36e+w8cRg/0IqU4SUSqb0JhVHWQJRYSn3Z0OcX2KG1b
C4F4h+sH6w3MK8pzLLgLzwLdCYq7D8l8wjNQbiqZYxSB1sktKI0dQQOCj3w2cGlyJXMPiGaWLqMg
QrVwBrr3WKUXKktKQMvVZBaUWnEzLNpYRaWkQiQvQPu5yDPVUPqCJXNBcCdVz6JyLIpyRAZORDxS
OzpbxXz9/v39/f1xHAyRVlV1n1XnnXeVDxyIqYEGXKLQ8bL4tUWOWYjKZGPaK80E1tQ6Jsl4WG0a
eGZJ0pO3m0LwvGkEz4tG8LxuBM/LRvC8agTP60bwvB4Ez+tG8LzuBc/rfvC8HgTP60HwvB4Ez+tB
8LweVM/rfvC8HgTP60HwvJ4Ez+tJ8LyeM8/refC8ngfP63kQvJ4Xz+t58LweBM/rQfC8HgTP60Hw
vJ4Fz+t58LyeB8/rfvC8fgTP6/4u+HphR6+2fPxWm5dWvPVGJrZC++Tz8oa1fWPtPdj2jbX3aNu3
xN5DY+8xsOczVTNVDFRBVRBVUBVEFVQFUQVVQVRBVRBVUBVEFVQFUQVVQVRBVRBVUBVUBVFBVRAV
RAVRAVQQFUQFUAFUABUAFUAFUAFUAFQAFQAVABVABUAFUAFUAFQAFUAFUAFUAFQAFUAFUAFUAFQA
FUAFUAFUAFUAFUAFUAFUAFUAFUAFUAFUAFUAFQAFQAFQAFQAFQAFQAFQAFQAFQAFQAFQAFQAFQAF
QAFQAFQAFQAFQAFQAFQAFQAFQAFQAFQAFQAFQ==
"""

# This is a base64-encoded, compressed binary of your app.py
# To decrypt: python decrypt_app.py

print("[ENCRYPTED APP] - Cannot view source code directly")
print("To run: python run_encrypted_app.py")
